const interest = [
  { "name" : "Hiking"},
  { "name" : "Camping"},
  { "name" : "Bird Watching"},
  { "name" : "Fishing"},
  { "name" : "Kayaking and Canoeing"},
  { "name" : "Rock Climbing"},
  { "name" : "Stargazing"},
  { "name" : "Wildlife Photography"},
  { "name" : "Backpacking"},
  { "name" : "Mountain Biking"},
  { "name" : "Nature Conservation"},
  { "name" : "Beachcombing"},
  { "name" : "Botany and Plant Study"},
  { "name" : "Gardening (Vegetable)"},
  { "name" : "Foraging Wild Edibles"},
  { "name" : "Sailing"},
  { "name" : "Horseback Riding"},
  { "name" : "Fossil Hunting"},
  { "name" : "Surfing"},
  { "name" : "Beekeeping"},
  { "name" : "Geocaching"},
  { "name" : "Landscape Photography"},
  { "name" : "Trail Running"},
  { "name" : "Tree Climbing"},
  { "name" : "Environmental Advocacy"},
  { "name" : "Mushroom Hunting"},
  { "name" : "Scuba Diving"},
  { "name" : "Snorkeling"},
  { "name" : "River Rafting"},
  { "name" : "Orienteering"},
  { "name" : "Painting (Oil)"},
  { "name" : "Drawing and Sketching"},
  { "name" : "Pottery and Ceramics"},
  { "name" : "Sculpting"},
  { "name" : "Knitting and Crocheting"},
  { "name" : "Sewing and Quilting"},
  { "name" : "Scrapbooking"},
  { "name" : "Calligraphy and Hand Lettering"},
  { "name" : "Woodworking"},
  { "name" : "Jewelry Making"},
  { "name" : "Embroidery"},
  { "name" : "Metalworking"},
  { "name" : "Candle Making"},
  { "name" : "Soap Making"},
  { "name" : "Origami"},
  { "name" : "Glassblowing"},
  { "name" : "Leathercraft"},
  { "name" : "Stained Glass Art"},
  { "name" : "Beadwork"},
  { "name" : "Macrame"},
  { "name" : "Paper Crafting"},
  { "name" : "Textile Dyeing"},
  { "name" : "Printmaking"},
  { "name" : "Basket Weaving"},
  { "name" : "Mosaic Art"},
  { "name" : "Resin Art"},
  { "name" : "Weaving and Looming"},
  { "name" : "Bookbinding"},
  { "name" : "Miniature Model Making"},
  { "name" : "Fiber Arts"},
  { "name" : "Playing a Musical Instrument (Guitar)"},
  { "name" : "Singing and Vocal Training"},
  { "name" : "Songwriting"},
  { "name" : "Music Production"},
  { "name" : "DJing"},
  { "name" : "Dance (Ballet Hip-Hop Ballroom etc.)"},
  { "name" : "Theater Acting"},
  { "name" : "Improvisational Comedy"},
  { "name" : "Stand-Up Comedy"},
  { "name" : "Opera Singing"},
  { "name" : "Music Composition"},
  { "name" : "Choreography"},
  { "name" : "Audio Engineering"},
  { "name" : "Musical Theater"},
  { "name" : "Spoken Word Poetry"},
  { "name" : "Voice Acting"},
  { "name" : "Mime"},
  { "name" : "Classical Music Appreciation"},
  { "name" : "Orchestral Conducting"},
  { "name" : "Public Speaking and Oratory Skills"},
  { "name" : "Lip Syncing"},
  { "name" : "Beatboxing"},
  { "name" : "Music Theory"},
  { "name" : "Record Collecting"},
  { "name" : "Concert Photography"},
  { "name" : "Dance Fitness (Zumba Jazzercise)"},
  { "name" : "Puppet Making and Puppeteering"},
  { "name" : "Busking (Street Performing)"},
  { "name" : "Digital Music Sampling"},
  { "name" : "Folk Dancing"},
  { "name" : "Running and Jogging"},
  { "name" : "Swimming"},
  { "name" : "Weightlifting"},
  { "name" : "Gymnastics"},
  { "name" : "Martial Arts (Karate Judo Taekwondo)"},
  { "name" : "Tennis"},
  { "name" : "Basketball"},
  { "name" : "Soccer"},
  { "name" : "Golf"},
  { "name" : "Baseball and Softball"},
  { "name" : "Cycling (Road Mountain)"},
  { "name" : "Skateboarding"},
  { "name" : "Skiing (Alpine Cross-Country)"},
  { "name" : "Snowboarding"},
  { "name" : "Yoga"},
  { "name" : "Pilates"},
  { "name" : "Fencing"},
  { "name" : "Archery"},
  { "name" : "Boxing"},
  { "name" : "Rowing"},
  { "name" : "Volleyball"},
  { "name" : "Badminton"},
  { "name" : "Rock Climbing (Indoor)"},
  { "name" : "Table Tennis"},
  { "name" : "Wrestling"},
  { "name" : "Bowling"},
  { "name" : "Sculling"},
  { "name" : "Squash"},
  { "name" : "Rugby"},
  { "name" : "Ultimate Frisbee"},
  { "name" : "Video Gaming (PC Console)"},
  { "name" : "Tabletop Gaming (D&D Warhammer)"},
  { "name" : "Board Games (Chess Monopoly Settlers of Catan)"},
  { "name" : "Card Games (Poker Bridge Solitaire)"},
  { "name" : "Puzzle Solving (Crossword Sudoku)"},
  { "name" : "Escape Rooms"},
  { "name" : "Collectible Card Games (Magic: The Gathering)"},
  { "name" : "Jigsaw Puzzles"},
  { "name" : "Brain Teasers and Logic Puzzles"},
  { "name" : "Miniature Wargaming"},
  { "name" : "Virtual Reality Gaming"},
  { "name" : "Speedcubing (Rubik's Cube)"},
  { "name" : "Word Search Puzzles"},
  { "name" : "Bingo"},
  { "name" : "eSports Watching and Participation"},
  { "name" : "Building Puzzle Boxes"},
  { "name" : "Role-Playing Games (RPGs)"},
  { "name" : "Memory Games"},
  { "name" : "Trivia and Quiz Games"},
  { "name" : "Scavenger Hunts"},
  { "name" : "Augmented Reality Gaming"},
  { "name" : "Fantasy Sports Leagues"},
  { "name" : "Chess Problem Solving"},
  { "name" : "Mahjong"},
  { "name" : "Fiction Reading (Novels Short Stories)"},
  { "name" : "Non-Fiction Reading (Biographies Memoirs)"},
  { "name" : "Poetry Writing and Appreciation"},
  { "name" : "Creative Writing (Short Stories Flash Fiction)"},
  { "name" : "Blogging and Vlogging"},
  { "name" : "Screenwriting"},
  { "name" : "Playwriting"},
  { "name" : "Essay Writing"},
  { "name" : "Journalism"},
  { "name" : "Reading Classic Literature"},
  { "name" : "Book Collecting"},
  { "name" : "Comic Book and Graphic Novel Reading"},
  { "name" : "Fan Fiction Writing"},
  { "name" : "Science Fiction and Fantasy Reading"},
  { "name" : "Mystery Novel Reading"},
  { "name" : "Memoir and Autobiography Writing"},
  { "name" : "Literary Analysis"},
  { "name" : "Writing for Social Media"},
  { "name" : "Editing and Proofreading"},
  { "name" : "Self-Publishing"},
  { "name" : "Travel Writing"},
  { "name" : "Horror and Thriller Reading"},
  { "name" : "Historical Fiction Reading"},
  { "name" : "Writing Poetry"},
  { "name" : "Magazine Reading (Science Fashion etc.)"},
  { "name" : "Philosophical Literature"},
  { "name" : "Short Story Anthologies"},
  { "name" : "Fictional Worldbuilding"},
  { "name" : "Nature Writing"},
  { "name" : "Book Club Participation"},
  { "name" : "Robotics and Electronics"},
  { "name" : "Astronomy and Stargazing"},
  { "name" : "Coding and Programming"},
  { "name" : "3D Printing"},
  { "name" : "Amateur Radio (Ham Radio)"},
  { "name" : "Model Rocketry"},
  { "name" : "Virtual Reality Development"},
  { "name" : "Drones and Drone Photography"},
  { "name" : "Space Exploration Interest"},
  { "name" : "Weather Observation"},
  { "name" : "Artificial Intelligence and Machine Learning"},
  { "name" : "Quantum Computing Basics"},
  { "name" : "Bioinformatics"},
  { "name" : "Data Science and Analysis"},
  { "name" : "Home Automation (Smart Home Tech)"},
  { "name" : "Cybersecurity and Ethical Hacking"},
  { "name" : "Paleontology and Fossil Collecting"},
  { "name" : "Collecting Minerals and Crystals"},
  { "name" : "Model Railroading"},
  { "name" : "Space and Planetary Science"},
  { "name" : "Cryptography"},
  { "name" : "Renewable Energy and Solar Power"},
  { "name" : "Astrophotography"},
  { "name" : "Internet of Things (IoT) Projects"},
  { "name" : "Nanotechnology"},
  { "name" : "Chemistry Experiments"},
  { "name" : "Science Fairs and Competitions"},
  { "name" : "Physics and Theoretical Physics"},
  { "name" : "Marine Biology"},
  { "name" : "Electronics Tinkering"},
  { "name" : "Solo Travel"},
  { "name" : "Road Tripping"},
  { "name" : "Cultural Travel"},
  { "name" : "Food Tourism"},
  { "name" : "Hiking and Trekking in Foreign Countries"},
  { "name" : "Backpacking Across Continents"},
  { "name" : "RV and Camper Travel"},
  { "name" : "Heritage Site Exploration"},
  { "name" : "Photography-Based Travel"},
  { "name" : "Off-the-Beaten-Path Travel"},
  { "name" : "Cruise Travel"},
  { "name" : "Adventure Tourism (Skydiving Zip-lining)"},
  { "name" : "Luxury Travel"},
  { "name" : "Exploring Small Towns"},
  { "name" : "History and Archaeology Travel"},
  { "name" : "Wildlife Safaris"},
  { "name" : "Camping in National Parks"},
  { "name" : "Snow Adventures (Skiing Snowboarding)"},
  { "name" : "Architectural Tours"},
  { "name" : "City Exploration and Urban Hikes"},
  { "name" : "Scenic Train Journeys"},
  { "name" : "Backpacking Through National Parks"},
  { "name" : "UNESCO World Heritage Site Visits"},
  { "name" : "Overland Adventure Travel"},
  { "name" : "Jungle and Rainforest Exploration"},
  { "name" : "Desert Expeditions"},
  { "name" : "Bike Touring"},
  { "name" : "Religious Pilgrimages"},
  { "name" : "Eco-Tourism"},
  { "name" : "Cultural Festivals and Events Travel"},
  { "name" : "Learning New Languages"},
  { "name" : "Public Speaking and Oratory"},
  { "name" : "Self-Help and Personal Development"},
  { "name" : "Speed Reading"},
  { "name" : "Memory Improvement Techniques"},
  { "name" : "Mind Mapping"},
  { "name" : "Critical Thinking Skills"},
  { "name" : "Life Coaching"},
  { "name" : "Financial Literacy"},
  { "name" : "Online Course Participation"},
  { "name" : "Skill-Building Workshops"},
  { "name" : "Study Techniques and Hacks"},
  { "name" : "Cognitive Psychology"},
  { "name" : "Problem-Solving Skills"},
  { "name" : "Meditation and Stress Reduction"},
  { "name" : "Personal Branding"},
  { "name" : "Emotional Intelligence"},
  { "name" : "Goal Setting and Achievement"},
  { "name" : "Personal Finance Management"},
  { "name" : "Developing Leadership Skills"},
  { "name" : "Learning Soft Skills"},
  { "name" : "Writing and Reflective Journaling"},
  { "name" : "Time Management"},
  { "name" : "Practicing Gratitude"},
  { "name" : "Setting Up Vision Boards"},
  { "name" : "Digital Organization and Productivity"},
  { "name" : "Career Development Planning"},
  { "name" : "Finding Life Purpose"},
  { "name" : "Learning Social Skills"},
  { "name" : "Developing Assertiveness"},
  { "name" : "Fashion Design"},
  { "name" : "Personal Styling"},
  { "name" : "Sewing and Tailoring"},
  { "name" : "Accessory Design (Bags Belts)"},
  { "name" : "DIY Clothing Alterations"},
  { "name" : "Fashion Blogging"},
  { "name" : "Sustainable Fashion Practices"},
  { "name" : "Makeup Artistry"},
  { "name" : "Nail Art"},
  { "name" : "Jewelry Design"},
  { "name" : "Cosplay and Costume Design"},
  { "name" : "Fashion Photography"},
  { "name" : "Modeling and Runway"},
  { "name" : "Capsule Wardrobe Creation"},
  { "name" : "Closet Organization"},
  { "name" : "Vintage Fashion Collection"},
  { "name" : "Wardrobe Styling for Photoshoots"},
  { "name" : "Fashion Illustration"},
  { "name" : "Trend Forecasting"},
  { "name" : "Personal Grooming"},
  { "name" : "Men's Fashion and Styling"},
  { "name" : "Fashion History"},
  { "name" : "Upcycling Old Clothing"},
  { "name" : "Seasonal Wardrobe Planning"},
  { "name" : "Styling for Plus Size"},
  { "name" : "Cultural Fashion (Traditional Wear)"},
  { "name" : "Hair Styling Techniques"},
  { "name" : "Thrift Shopping"},
  { "name" : "Wedding Styling"},
  { "name" : "Luxury Fashion Brands Exploration"},
  { "name" : "Social and Cultural Interests"},
  { "name" : "Volunteering and Community Service"},
  { "name" : "Genealogy and Ancestry Research"},
  { "name" : "Cultural Studies and Anthropology"},
  { "name" : "Language Exchange"},
  { "name" : "Visiting Museums and Art Galleries"},
  { "name" : "Attending Cultural Festivals"},
  { "name" : "Political Activism"},
  { "name" : "History Research and Study"},
  { "name" : "Philosophy and Ethics"},
  { "name" : "Exploring Different Religions"},
  { "name" : "Social Justice and Advocacy"},
  { "name" : "Public Policy Awareness"},
  { "name" : "Folklore and Mythology Study"},
  { "name" : "Attending Literary Festivals"},
  { "name" : "Attending Theater Performances"},
  { "name" : "Historical Reenactments"},
  { "name" : "Interfaith Dialogue and Study"},
  { "name" : "International Relations Awareness"},
  { "name" : "Social Work"},
  { "name" : "Human Rights Activism"},
  { "name" : "International Cuisine Exploration"},
  { "name" : "Local History Research"},
  { "name" : "Sociology and Social Behavior"},
  { "name" : "Study of Ancient Civilizations"},
  { "name" : "Street Art Appreciation"},
  { "name" : "Independent Film Watching"},
  { "name" : "Peace Studies and Conflict Resolution"},
  { "name" : "Studying Ancient Scripts and Languages"},
  { "name" : "Cultural Anthropology"},
  { "name" : "Attending Opera Performances"},
  { "name" : "Dog Training and Obedience"},
  { "name" : "Cat Care and Grooming"},
  { "name" : "Exotic Pet Care"},
  { "name" : "Aquascaping for Fish Tanks"},
  { "name" : "Bird Watching and Bird Care"},
  { "name" : "Dog Walking"},
  { "name" : "Pet Grooming Skills"},
  { "name" : "Animal Rescue Volunteering"},
  { "name" : "Horseback Riding and Horse Care"},
  { "name" : "Pet Photography"},
  { "name" : "Reptile and Amphibian Care"},
  { "name" : "Pet Sitting"},
  { "name" : "Animal Behavior Observation"},
  { "name" : "Building Animal Habitats"},
  { "name" : "Pet Nutrition and Diet Planning"},
  { "name" : "Breeding and Raising Small Animals"},
  { "name" : "Participating in Pet Shows"},
  { "name" : "Aquatic Pet Keeping"},
  { "name" : "Dog Agility Training"},
  { "name" : "Pet Fashion and Accessories"},
  { "name" : "Animal Shelter Support"},
  { "name" : "Rabbit and Small Mammal Care"},
  { "name" : "Animal-Assisted Therapy"},
  { "name" : "Pet Safety and First Aid"},
  { "name" : "Animal Rights Awareness"},
  { "name" : "Learning Animal Communication"},
  { "name" : "Community Dog Parks and Socializing"},
  { "name" : "Building Pet Enrichment Toys"},
  { "name" : "Rescue and Adoption Awareness"},
  { "name" : "Training Therapy Animals"},
  { "name" : "Finance and Investment Interests"},
  { "name" : "Stock Market Investing"},
  { "name" : "Real Estate Investment"},
  { "name" : "Cryptocurrency Trading"},
  { "name" : "Personal Budgeting"},
  { "name" : "Saving and Wealth Building"},
  { "name" : "Collecting Gold and Precious Metals"},
  { "name" : "Mutual Funds and ETFs"},
  { "name" : "Retirement Planning"},
  { "name" : "Forex Trading"},
  { "name" : "Dividend Investing"},
  { "name" : "Passive Income Streams"},
  { "name" : "Portfolio Management"},
  { "name" : "Angel Investing"},
  { "name" : "Peer-to-Peer Lending"},
  { "name" : "Tax Planning and Strategies"},
  { "name" : "Sustainable Investing (ESG)"},
  { "name" : "Financial Literacy Education"},
  { "name" : "Value Investing"},
  { "name" : "Financial Planning for Families"},
  { "name" : "Options and Futures Trading"},
  { "name" : "Venture Capital Basics"},
  { "name" : "Learning Financial Analysis"},
  { "name" : "Rental Property Management"},
  { "name" : "Stock Analysis and Valuation"},
  { "name" : "Compound Interest Savings"},
  { "name" : "Budgeting for Travel and Leisure"},
  { "name" : "Creating Emergency Funds"},
  { "name" : "Debt Reduction Techniques"},
  { "name" : "Understanding Inflation"},
  { "name" : "Crowdfunding Investments"},
  { "name" : "Automotive and Mechanical Interests"},
  { "name" : "Car Restoration and Modification"},
  { "name" : "Motorcycle Maintenance and Riding"},
  { "name" : "Classic Car Collecting"},
  { "name" : "Off-Road Driving"},
  { "name" : "Electric Vehicle Technology"},
  { "name" : "Automotive Detailing"},
  { "name" : "Go-Kart Racing"},
  { "name" : "Vehicle Tuning and Performance"},
  { "name" : "Auto Body Repair"},
  { "name" : "DIY Car Repairs"},
  { "name" : "Building and Maintaining Bicycles"},
  { "name" : "Engine Repair and Tuning"},
  { "name" : "Learning Automotive Electronics"},
  { "name" : "Understanding Car Suspension Systems"},
  { "name" : "Collecting Die-Cast Models"},
  { "name" : "Antique Vehicle Restoration"},
  { "name" : "Car Audio Installation"},
  { "name" : "Racing Simulator Setups"},
  { "name" : "Road Trip Planning"},
  { "name" : "Driving on Racing Tracks"},
  { "name" : "Boat Maintenance and Repair"},
  { "name" : "Drone Mechanics and Flying"},
  { "name" : "Participating in Car Shows"},
  { "name" : "DIY Engine Rebuilds"},
  { "name" : "Designing Custom Car Interiors"},
  { "name" : "Tire and Brake Maintenance"},
  { "name" : "Car Photography"},
  { "name" : "Collecting License Plates"},
  { "name" : "Tinkering with Small Engines"},
  { "name" : "Drone Racing"},
  { "name" : "Entrepreneurship and Business Interests"},
  { "name" : "Starting a Small Business"},
  { "name" : "Freelancing"},
  { "name" : "E-commerce Store Management"},
  { "name" : "Blogging as a Business"},
  { "name" : "Personal Branding"},
  { "name" : "Networking and Business Connections"},
  { "name" : "Consulting"},
  { "name" : "Building Passive Income"},
  { "name" : "Dropshipping"},
  { "name" : "Crafting a Business Plan"},
  { "name" : "Product Development"},
  { "name" : "Digital Marketing"},
  { "name" : "Affiliate Marketing"},
  { "name" : "Business Analytics"},
  { "name" : "Social Media Management"},
  { "name" : "Business Strategy Planning"},
  { "name" : "Crowdfunding Campaigns"},
  { "name" : "Venture Capital Exploration"},
  { "name" : "Customer Experience Design"},
  { "name" : "Public Relations for Small Businesses"},
  { "name" : "Learning Accounting Basics"},
  { "name" : "Human Resources Management"},
  { "name" : "Starting a Franchise"},
  { "name" : "Financial Forecasting"},
  { "name" : "Market Research"},
  { "name" : "Customer Relationship Management"},
  { "name" : "Sales Funnel Creation"},
  { "name" : "Business Writing and Blogging"},
  { "name" : "Event Planning for Businesses"},
  { "name" : "Negotiation Skills Development"},
  { "name" : "Parenting and Family Interests"},
  { "name" : "Family Travel Planning"},
  { "name" : "Homeschooling Techniques"},
  { "name" : "Parenting for Different Age Groups"},
  { "name" : "Child Development and Learning"},
  { "name" : "Baby Care and Infant Development"},
  { "name" : "Crafting with Kids"},
  { "name" : "Organizing Family Events"},
  { "name" : "Family Photography"},
  { "name" : "Parenting Support Groups"},
  { "name" : "Teaching Kids Financial Literacy"},
  { "name" : "Family Fitness and Outdoor Activities"},
  { "name" : "Positive Parenting Techniques"},
  { "name" : "Nutrition and Meal Planning for Families"},
  { "name" : "Navigating Parenthood and Career Balance"},
  { "name" : "Building Family Traditions"},
  { "name" : "Supporting Children's Mental Health"},
  { "name" : "Special Needs Parenting"},
  { "name" : "Family Game Nights"},
  { "name" : "Teaching Kids Practical Skills"},
  { "name" : "Pet Parenting for Families"},
  { "name" : "Coordinating Family Volunteering"},
  { "name" : "Preparing for New Baby"},
  { "name" : "Family Recipe Collecting"},
  { "name" : "Family Scrapbooking"},
  { "name" : "Parenting Through Adolescence"},
  { "name" : "Toddler Activities and Crafts"},
  { "name" : "Storytelling with Kids"},
  { "name" : "Preparing Kids for School"},
  { "name" : "DIY Family Holiday Decor"},
  { "name" : "Family Camping and Hiking"},
  { "name" : "Collectible and Memorabilia Interests"},
  { "name" : "Vintage Toy Collecting"},
  { "name" : "Antique Furniture Collecting"},
  { "name" : "Collecting Movie Posters"},
  { "name" : "Sports Cards Collecting"},
  { "name" : "Rare Book Collecting"},
  { "name" : "Collecting Artifacts and Relics"},
  { "name" : "Autograph Collecting"},
  { "name" : "Collecting Vintage Advertising"},
  { "name" : "Coin and Currency Collection"},
  { "name" : "Firearms Collecting (Historical)"},
  { "name" : "Souvenir Collecting from Travels"},
  { "name" : "Collecting War Memorabilia"},
  { "name" : "Fountain Pen Collecting"},
  { "name" : "Glass Bottle Collecting"},
  { "name" : "Thimble Collecting"},
  { "name" : "Historical Documents and Manuscripts"},
  { "name" : "Vintage Electronics Collecting"},
  { "name" : "Political Memorabilia"},
  { "name" : "Collecting Vintage Tools"},
  { "name" : "Collecting Limited Edition Figures"},
  { "name" : "Collecting Maps and Atlases"},
  { "name" : "Doll Collecting"},
  { "name" : "Collecting Perfume Bottles"},
  { "name" : "Record and Vinyl Collecting"},
  { "name" : "Collecting Casino Chips"},
  { "name" : "Marbles Collecting"},
  { "name" : "Antique Clocks Collecting"},
  { "name" : "Medal and Badge Collecting"},
  { "name" : "Vintage Posters and Prints"},
  { "name" : "Model Train Collecting"},
  { "name" : "Writing Interests"},
  { "name" : "Novels and Stories"},
  { "name" : "Reading Classic Literature"},
  { "name" : "Writing Poetry and Prose"},
  { "name" : "Fiction Writing (Fantasy Sci-Fi etc.)"},
  { "name" : "Scriptwriting and Screenwriting"},
  { "name" : "Book Club Participation"},
  { "name" : "Fan Fiction Writing"},
  { "name" : "Memoir Writing"},
  { "name" : "Writing Children's Books"},
  { "name" : "Editing and Proofreading"},
  { "name" : "Literary Analysis and Critique"},
  { "name" : "Reading Historical Fiction"},
  { "name" : "Flash Fiction Writing"},
  { "name" : "Writing Creative Nonfiction"},
  { "name" : "Haiku and Short Poetry Writing"},
  { "name" : "Reading and Analyzing Philosophy"},
  { "name" : "Reading Contemporary Fiction"},
  { "name" : "Writing Mystery and Thriller"},
  { "name" : "Crafting Fantasy Worlds"},
  { "name" : "Travel Writing and Blogging"},
  { "name" : "Reading Biographies and Memoirs"},
  { "name" : "Self-Publishing Books"},
  { "name" : "Writing Young Adult Fiction"},
  { "name" : "Writing Comic Strips and Graphic Novels"},
  { "name" : "Experimental and Abstract Writing"},
  { "name" : "Writing for Magazines and Journals"},
  { "name" : "Reading Sci-Fi and Fantasy"},
  { "name" : "Short Story Writing"},
  { "name" : "Literary Event Attendance"},
  { "name" : "Writing Prompts and Challenges"},
  { "name" : "Philosophy Psychology and Self-Reflection Interests"},
  { "name" : "Philosophy and Ethical Studies"},
  { "name" : "Psychology and Human Behavior"},
  { "name" : "Personal Development Journaling"},
  { "name" : "Cognitive Science and Neuroscience"},
  { "name" : "Life Coaching and Mentorship"},
  { "name" : "Practicing Mindfulness"},
  { "name" : "Meditation and Self-Reflection"},
  { "name" : "Analyzing Dreams and Symbolism"},
  { "name" : "Studying Stoicism"},
  { "name" : "Positive Psychology"},
  { "name" : "Self-Awareness Practices"},
  { "name" : "Writing Affirmations and Manifestations"},
  { "name" : "Practicing Gratitude"},
  { "name" : "Exploring Existentialism"},
  { "name" : "Hypnotherapy Basics"},
  { "name" : "Analyzing Personality Types (MBTI Enneagram)"},
  { "name" : "Studying Eastern Philosophies (Zen Taoism)"},
  { "name" : "Practicing Law of Attraction"},
  { "name" : "Exploring Spirituality"},
  { "name" : "Self-Discovery Activities"},
  { "name" : "Deep Listening and Empathy"},
  { "name" : "Exploring Ancient Wisdom Texts"},
  { "name" : "Automotive Detailing"},
  { "name" : "Go-Kart Racing"},
  { "name" : "Vehicle Tuning and Performance"},
  { "name" : "Auto Body Repair"},
  { "name" : "DIY Car Repairs"},
  { "name" : "Building and Maintaining Bicycles"},
  { "name" : "Engine Repair and Tuning"},
  { "name" : "Journaling for Mental Clarity"},
  { "name" : "Practicing Self-Love and Acceptance"},
  { "name" : "Studying Behavioral Economics"},
  { "name" : "Resilience Building and Coping Skills"},
  { "name" : "Practicing Kindness and Compassion"},
  { "name" : "Moral Philosophy"},
  { "name" : "Studying Religious and Mystical Texts"},
  { "name" : "Counseling and Reflective Listening"},
  { "name" : "Language and Communication Interests"},
  { "name" : "Learning New Languages"},
  { "name" : "Practicing Public Speaking"},
  { "name" : "Sign Language Basics"},
  { "name" : "Debating and Argumentation"},
  { "name" : "Storytelling Techniques"},
  { "name" : "Conversation Skills Development"},
  { "name" : "Speech Writing and Presentation"},
  { "name" : "Practicing Charisma and Influence"},
  { "name" : "Writing and Performing Spoken Word Poetry"},
  { "name" : "Accent Training"},
  { "name" : "Social Etiquette and Manners"},
  { "name" : "Nonverbal Communication Mastery"},
  { "name" : "Personal Branding and Networking"},
  { "name" : "Teaching Language to Others"},
  { "name" : "Writing Persuasive Essays"},
  { "name" : "Verbal Reasoning and Logic"},
  { "name" : "Language Exchange Programs"},
  { "name" : "Practicing Negotiation Skills"},
  { "name" : "Foreign Language Translation"},
  { "name" : "Podcasting and Broadcasting"},
  { "name" : "Vocal Training and Projection"},
  { "name" : "Conducting Interviews"},
  { "name" : "Cultural Communication Skills"},
  { "name" : "Cross-Cultural Communication"},
  { "name" : "Reading and Interpreting Body Language"},
  { "name" : "Video Conferencing Skills"},
  { "name" : "Media and Journalism"},
  { "name" : "Writing Editorials and Opinion Pieces"},
  { "name" : "Enhancing Conversational Intelligence"},
  { "name" : "Comedy and Improvisation Skills"},
  { "name" : "Meditation Practices"},
  { "name" : "Yoga for Spiritual Growth"},
  { "name" : "Astrology and Horoscopes"},
  { "name" : "Numerology"},
  { "name" : "Chakra Healing and Balancing"},
  { "name" : "Tarot Card Reading"},
  { "name" : "Crystal Healing"},
  { "name" : "Energy Healing and Reiki"},
  { "name" : "Mindfulness and Mindful Living"},
  { "name" : "Shamanic Journeying"},
  { "name" : "Aura Reading"},
  { "name" : "Feng Shui and Space Cleansing"},
  { "name" : "Studying Esoteric and Occult Practices"},
  { "name" : "Sound Healing with Singing Bowls"},
  { "name" : "Manifestation Techniques"},
  { "name" : "Guided Visualization"},
  { "name" : "Studying World Religions"},
  { "name" : "Sacred Geometry"},
  { "name" : "Runes and Divination"},
  { "name" : "Akashic Records Exploration"},
  { "name" : "Breathwork and Pranayama"},
  { "name" : "Practicing Compassion Meditation"},
  { "name" : "Past Life Regression"},
  { "name" : "Mediumship Development"},
  { "name" : "Conscious Dreaming and Lucid Dreaming"},
  { "name" : "Learning Herbalism and Plant Medicine"},
  { "name" : "Exploring Ancient Spiritual Texts"},
  { "name" : "Learning Mantras and Chanting"},
  { "name" : "Practicing Gratitude Journals"},
  { "name" : "Sacred Rituals and Ceremonies"},
  { "name" : "Film TV and Media Interests"},
  { "name" : "Watching Classic Films"},
  { "name" : "Movie Reviews and Critiques"},
  { "name" : "Documentary Watching"},
  { "name" : "Animation and CGI"},
  { "name" : "Collecting Film Memorabilia"},
  { "name" : "Cinematography Appreciation"},
  { "name" : "Attending Film Festivals"},
  { "name" : "Watching Indie and Art Films"},
  { "name" : "Film History and Theory"},
  { "name" : "Screenwriting for Movies and TV"},
  { "name" : "Streaming TV Shows and Series"},
  { "name" : "Creating YouTube Content"},
  { "name" : "Voice Acting and Dubbing"},
  { "name" : "Video Editing"},
  { "name" : "Directing Short Films"},
  { "name" : "Creating Movie Fan Edits"},
  { "name" : "Podcast Listening"},
  { "name" : "Vlogging"},
  { "name" : "Video Production Techniques"},
  { "name" : "Watching Foreign Films"},
  { "name" : "Analyzing Film Scores"},
  { "name" : "Watching Theater Performances"},
  { "name" : "Behind-the-Scenes Filmmaking"},
  { "name" : "Watching Animated Shows"},
  { "name" : "Binge-Watching Series"},
  { "name" : "Acting and Auditioning"},
  { "name" : "Learning Film Special Effects"},
  { "name" : "Sound Design and Foley Art"},
  { "name" : "Watching Nature Documentaries"},
  { "name" : "Media Studies and Journalism"},
  { "name" : "Adventure and Extreme Sports Interests"},
  { "name" : "Skydiving and Parachuting"},
  { "name" : "Rock Climbing (Bouldering Free Climbing)"},
  { "name" : "Scuba Diving and Snorkeling"},
  { "name" : "Paragliding"},
  { "name" : "Whitewater Rafting"},
  { "name" : "Mountaineering"},
  { "name" : "Snowboarding"},
  { "name" : "Ice Climbing"},
  { "name" : "Free Diving"},
  { "name" : "BMX and Freestyle Biking"},
  { "name" : "BASE Jumping"},
  { "name" : "Surfing Big Waves"},
  { "name" : "Hang Gliding"},
  { "name" : "Kite Surfing"},
  { "name" : "Caving and Spelunking"},
  { "name" : "Downhill Mountain Biking"},
  { "name" : "Sandboarding"},
  { "name" : "Windsurfing"},
  { "name" : "Bungee Jumping"},
  { "name" : "Skateboarding Tricks"},
  { "name" : "Extreme Hiking and Trekking"},
  { "name" : "Rally Racing"},
  { "name" : "Ultra-Running (Endurance Races)"},
  { "name" : "Polar Expeditions"},
  { "name" : "Cliff Diving"},
  { "name" : "Gliding and Soaring"},
  { "name" : "Longboarding"},
  { "name" : "Barefoot Running"},
  { "name" : "Cave Diving"},
  { "name" : "Desert Racing"},
  { "name" : "Environmental and Sustainable Living Interests"},
  { "name" : "Zero Waste Living"},
  { "name" : "Organic Gardening"},
  { "name" : "Composting Techniques"},
  { "name" : "Upcycling and Recycling Projects"},
  { "name" : "Permaculture Design"},
  { "name" : "Sustainable Architecture"},
  { "name" : "Renewable Energy Awareness"},
  { "name" : "Ecotourism"},
  { "name" : "Plastic-Free Lifestyle"},
  { "name" : "Plant-Based Eating"},
  { "name" : "Urban Gardening and Vertical Farms"},
  { "name" : "Supporting Local Farmers"},
  { "name" : "Minimalist Living"},
  { "name" : "Wildlife Conservation Volunteering"},
  { "name" : "Bee and Pollinator Gardening"},
  { "name" : "Community Clean-Up Events"},
  { "name" : "Environmental Activism"},
  { "name" : "Watershed Restoration"},
  { "name" : "Seed Saving and Exchange"},
  { "name" : "DIY Natural Household Products"},
  { "name" : "Eco-Friendly Fashion Choices"},
  { "name" : "Natural Cleaning Solutions"},
  { "name" : "Sustainable Fashion Design"},
  { "name" : "Water Conservation Techniques"},
  { "name" : "Studying Environmental Science"},
  { "name" : "Tree Planting Initiatives"},
  { "name" : "Rainwater Harvesting"},
  { "name" : "Organic Beekeeping"},
  { "name" : "Educating on Climate Change"},
  { "name" : "Advocating for Renewable Energy"},
  { "name" : "DIY and Crafting Hobbies"},
  { "name" : "Candle Making"},
  { "name" : "Soap Making"},
  { "name" : "DIY Home Decor"},
  { "name" : "Furniture Refinishing"},
  { "name" : "Paper Crafting (Origami Scrapbooking)"},
  { "name" : "Crochet and Knitting"},
  { "name" : "Embroidery and Needlework"},
  { "name" : "Sewing and Tailoring"},
  { "name" : "Resin Art Creations"},
  { "name" : "Polymer Clay Crafts"},
  { "name" : "Woodworking Projects"},
  { "name" : "Beading and Jewelry Making"},
  { "name" : "Calligraphy and Hand Lettering"},
  { "name" : "Pottery and Ceramic Art"},
  { "name" : "Macrame Wall Hangings"},
  { "name" : "Basket Weaving"},
  { "name" : "Glass Painting"},
  { "name" : "Wood Burning (Pyrography)"},
  { "name" : "Fabric Dyeing and Tie-Dye"},
  { "name" : "Miniature Building (Dollhouses Models)"},
  { "name" : "Upcycling Furniture"},
  { "name" : "Lace Making"},
  { "name" : "Shadow Box Art"},
  { "name" : "Quilting and Patchwork"},
  { "name" : "DIY Terrariums"},
  { "name" : "Mosaic Art Creations"},
  { "name" : "Flower Pressing"},
  { "name" : "Scrap Wood Crafts"},
  { "name" : "Dreamcatcher Making"},
  { "name" : "Mixed Media Art"},
  { "name" : "Hobbies Related to Animals and Wildlife"},
  { "name" : "Wildlife Photography"},
  { "name" : "Bird Watching"},
  { "name" : "Dog Training and Obedience"},
  { "name" : "Cat Care and Training"},
  { "name" : "Horseback Riding"},
  { "name" : "Aquarium and Fishkeeping"},
  { "name" : "Beekeeping"},
  { "name" : "Falconry"},
  { "name" : "Reptile Keeping"},
  { "name" : "Animal Rescue Volunteering"},
  { "name" : "Pet Grooming"},
  { "name" : "Animal Behavior Observation"},
  { "name" : "Exotic Pet Care"},
  { "name" : "Dog Agility Training"},
  { "name" : "Dog Walking"},
  { "name" : "Building Animal Habitats"},
  { "name" : "Small Mammal Care (Rabbits Hamsters)"},
  { "name" : "Farm Animal Care"},
  { "name" : "Wildlife Conservation Projects"},
  { "name" : "Animal Assisted Therapy"},
  { "name" : "Pet Photography"},
  { "name" : "Aquarium Aquascaping"},
  { "name" : "Fostering Shelter Animals"},
  { "name" : "Rabbit Showmanship"},
  { "name" : "Working with Therapy Dogs"},
  { "name" : "Studying Animal Communication"},
  { "name" : "Raising Guide Dogs"},
  { "name" : "Chicken Keeping and Coop Building"},
  { "name" : "Learning Veterinary Basics (Non-Professional)"},
  { "name" : "Chess Strategy and Tactics"},
  { "name" : "Poker Strategy and Bluffing"},
  { "name" : "Go (Weiqi) Game Techniques"},
  { "name" : "Sudoku Puzzles"},
  { "name" : "Crossword Puzzle Solving"},
  { "name" : "Bridge Card Game"},
  { "name" : "Jigsaw Puzzles"},
  { "name" : "Scrabble and Word Games"},
  { "name" : "Trivia and Quiz Games"},
  { "name" : "Rubik's Cube and Speedcubing"},
  { "name" : "Strategy Board Games (Risk Catan)"},
  { "name" : "Backgammon"},
  { "name" : "Pinochle Card Game"},
  { "name" : "Memory Games"},
  { "name" : "Mind Mapping and Visualization"},
  { "name" : "Logic Puzzles and Riddles"},
  { "name" : "Mahjong"},
  { "name" : "Codebreaking and Cryptography"},
  { "name" : "Fantasy Sports Drafting"},
  { "name" : "Whist Card Game"},
  { "name" : "Mancala and Traditional Games"},
  { "name" : "Darts and Accuracy Games"},
  { "name" : "Real-Time Strategy Games"},
  { "name" : "Strategic War Games (Miniature)"},
  { "name" : "Competitive Card Games (Magic: The Gathering)"},
  { "name" : "Collecting and Solving Puzzle Boxes"},
  { "name" : "Chess Problem Solving"},
  { "name" : "Kendoku Puzzles"},
  { "name" : "Contract Bridge"},
  { "name" : "Solitaire Variants"},
  { "name" : "Philosophy and Ethical Studies"},
  { "name" : "Theoretical Physics"},
  { "name" : "Mathematics and Number Theory"},
  { "name" : "Chemistry Experiments"},
  { "name" : "Psychology and Human Behavior"},
  { "name" : "Archaeology"},
  { "name" : "Linguistics"},
  { "name" : "Astronomy and Space Science"},
  { "name" : "Genealogy and Family History"},
  { "name" : "Literature Analysis"},
  { "name" : "History and Ancient Civilizations"},
  { "name" : "Anthropology"},
  { "name" : "Political Science"},
  { "name" : "Art History"},
  { "name" : "Economics and Trade Theory"},
  { "name" : "Studying Law and Legal Systems"},
  { "name" : "Sociology and Social Behavior"},
  { "name" : "Cryptography and Coding Theory"},
  { "name" : "Studying Neuroscience"},
  { "name" : "Environmental Science"},
  { "name" : "Cultural Anthropology"},
  { "name" : "Bioinformatics"},
  { "name" : "Exploring World Religions"},
  { "name" : "Social Psychology"},
  { "name" : "Analyzing Historic Texts"},
  { "name" : "Quantum Mechanics"},
  { "name" : "Ethics and Moral Philosophy"},
  { "name" : "Biomedical Engineering Concepts"},
  { "name" : "Intellectual Debates"},
  { "name" : "Study of Mythology and Folklore"},
  { "name" : "Volunteering at Animal Shelters"},
  { "name" : "Environmental Cleanup Efforts"},
  { "name" : "Disaster Relief Volunteering"},
  { "name" : "Donating and Organizing Blood Drives"},
  { "name" : "Community Garden Projects"},
  { "name" : "Organizing Fundraising Events"},
  { "name" : "Mentorship Programs for Youth"},
  { "name" : "Teaching Literacy"},
  { "name" : "Supporting Local Food Banks"},
  { "name" : "Elderly Care Volunteering"},
  { "name" : "Hospital Volunteering"},
  { "name" : "Refugee Support Services"},
  { "name" : "Building Homes for Habitat for Humanity"},
  { "name" : "Providing Free Tutoring"},
  { "name" : "Anti-Bullying Campaigns"},
  { "name" : "Organizing Donation Drives"},
  { "name" : "Advocating for Human Rights"},
  { "name" : "Mental Health Awareness"},
  { "name" : "Art Therapy Volunteering"},
  { "name" : "Supporting After-School Programs"},
  { "name" : "Organizing Book Drives"},
  { "name" : "Social Work with Families"},
  { "name" : "Teaching Financial Literacy"},
  { "name" : "Volunteering in Rural Development"},
  { "name" : "Mentoring Small Business Owners"},
  { "name" : "Providing Tech Assistance to Nonprofits"},
  { "name" : "Public Health Volunteering"},
  { "name" : "Women’s Rights Advocacy"},
  { "name" : "LGBTQ+ Support and Advocacy"},
  { "name" : "Youth Leadership Development"},
  { "name" : "Ballet Dancing"},
  { "name" : "Hip-Hop Dancing"},
    { "name" : "Ballroom Dancing (Salsa, Tango)"},
    { "name" : "Contemporary Dance"},
    { "name" : "Jazz Dance"},
    { "name" : "Tap Dancing"},
    { "name" : "Breakdancing"},
    { "name" : "Belly Dancing"},
    { "name" : "Folk Dancing (Irish, Greek, etc.)"},
    { "name" : "Swing Dancing"},
    { "name" : "Latin Dance (Bachata, Merengue)"},
    { "name" : "Pole Dancing"},
    { "name" : "Freestyle Dance"},
    { "name" : "Cultural Dance (Flamenco, Bollywood)"},
    { "name" : "Choreography and Dance Creation"},
    { "name" : "Dance Fitness (Zumba, Jazzercise)"},
    { "name" : "Competitive Dancing"},
    { "name" : "Dance Battles and Competitions"},
    { "name" : "Lyrical Dance"},
    { "name" : "Dance on Social Media (TikTok, Reels)"},
    { "name" : "Opera Singing"},
    { "name" : "Choir and Group Singing"},
    { "name" : "Jazz Singing"},
    { "name" : "Classical Singing"},
    { "name" : "Pop Singing"},
    { "name" : "Rap and Hip-Hop Vocals"},
    { "name" : "Musical Theater Singing"},
    { "name" : "Folk and Cultural Singing"},
    { "name" : "Rock and Alternative Singing"},
    { "name" : "Karaoke"},
    { "name" : "Vocal Training and Technique"},
    { "name" : "Acapella Singing"},
    { "name" : "Songwriting and Lyric Writing"},
    { "name" : "Harmonizing and Backing Vocals"},
    { "name" : "Performing Cover Songs"},
    { "name" : "Sound Cloud and Music Sharing"},
    { "name" : "Singing Competitions"},
    { "name" : "Recording Vocals at Home"},
    { "name" : "Social Media Music Covers"},
    { "name" : "Voice Exercises and Warm-Ups"},
    { "name" : "Theater Acting"},
    { "name" : "Improv Comedy"},
    { "name" : "Film and Television Acting"},
    { "name" : "Method Acting"},
    { "name" : "Stand-Up Comedy"},
    { "name" : "Monologue Practice"},
    { "name" : "Voice Acting and Dubbing"},
    { "name" : "Commercial Acting"},
    { "name" : "Acting for Musicals"},
    { "name" : "Physical Comedy"},
    { "name" : "Performing in Skits and Sketches"},
    { "name" : "Acting in Web Series"},
    { "name" : "Character Development for Acting"},
    { "name" : "Audition Preparation"},
    { "name" : "Studying Classic Plays"},
    { "name" : "Acting in Short Films"},
    { "name" : "Comedy Writing"},
    { "name" : "Drama Clubs and Local Theater"},
    { "name" : "Hosting and MC Skills"},
    { "name" : "Stand-Up Comedy"},
    { "name" : "Sketch Comedy Writing"},
    { "name" : "Physical Comedy and Slapstick"},
    { "name" : "Satire and Parody Creation"},
    { "name" : "Comedy Podcasting"},
    { "name" : "Comedy Vlogging"},
    { "name" : "Internet Meme Creation"},
    { "name" : "Dark Comedy"},
    { "name" : "Political Satire"},
    { "name" : "Improvisational Comedy"},
    { "name" : "Comedy Scriptwriting"},
    { "name" : "Roasting and Comedy Battles"},
    { "name" : "Impressions and Celebrity Mimicry"},
    { "name" : "Comedy Acting in Film"},
    { "name" : "Writing Comedy Monologues"},
    { "name" : "Observational Humor"},
    { "name" : "Social Media Comedy (TikTok, Instagram Reels)"},
    { "name" : "Creating Viral Comedy Skits"},
    { "name" : "Comedy Sound Bites and Voiceovers"},
    { "name" : "Animation Comedy (Voices, Storylines)"},
    { "name" : "Vlogging and Video Blogging"},
    { "name" : "Short Video Creation (TikTok, Instagram Reels)"},
    { "name" : "Content Creation for YouTube"},
    { "name" : "Influencer Marketing and Branding"},
    { "name" : "Storytelling for Social Media"},
    { "name" : "Editing Short Videos"},
    { "name" : "Creating DIY Tutorials for Social Media"},
    { "name" : "Live Streaming (YouTube, Instagram, Twitch)"},
    { "name" : "Social Media Challenges"},
    { "name" : "Scripted Content for TikTok"},
    { "name" : "Viral Content Strategy"},
    { "name" : "Social Media Trends Analysis"},
    { "name" : "Creative Transitions in Short Videos"},
    { "name" : "Video Filters and Effects"},
    { "name" : "Engaging with Social Media Fans"},
    { "name" : "Interactive Social Media Content"},
    { "name" : "Fitness and Health Influencing"},
    { "name" : "Lifestyle Blogging on Social Platforms"},
    { "name" : "Music and Lip Syncing Videos"},
    { "name" : "Behind-the-Scenes Content"},
    { "name" : "Cinematography for Short Films"},
    { "name" : "Photography for Social Media"},
    { "name" : "Video Montage Creation"},
    { "name" : "Motion Graphics for Short Videos"},
    { "name" : "Graphic Design for Social Media Posts"},
    { "name" : "Animation for Short Clips"},
    { "name" : "Visual Storytelling Techniques"},
    { "name" : "Building Digital Portfolios"},
    { "name" : "Green Screen Effects"},
    { "name" : "Character Animation (2D and 3D)"},
    { "name" : "Creating Infographics"},
    { "name" : "Interactive Digital Art"},
    { "name" : "Digital Collage for Social Media"},
    { "name" : "Visual Content Strategy"},
    { "name" : "Creating Visual Effects (VFX)"},
    { "name" : "Artistic Editing Techniques"},
    { "name" : "Typography Design"},
    { "name" : "Stop-Motion Animation"},
    { "name" : "Sound Design and Foley for Video"},
    { "name" : "Mixed Media Content Creation"}
  ];

export default interest;