const province = [
  { "name": "Andhra Pradesh", "code": "ap", "countryCode": "IND" },
  { "name": "Arunachal Pradesh", "code": "ar", "countryCode": "IND" },
  { "name": "Assam", "code": "as", "countryCode": "IND" },
  { "name": "Bihar", "code": "br", "countryCode": "IND" },
  { "name": "Chhattisgarh", "code": "ct", "countryCode": "IND" },
  { "name": "Goa", "code": "ga", "countryCode": "IND" },
  { "name": "Gujarat", "code": "gj", "countryCode": "IND" },
  { "name": "Haryana", "code": "hr", "countryCode": "IND" },
  { "name": "Himachal Pradesh", "code": "hp", "countryCode": "IND" },
  { "name": "Jharkhand", "code": "jh", "countryCode": "IND" },
  { "name": "Karnataka", "code": "ka", "countryCode": "IND" },
  { "name": "Kerala", "code": "kl", "countryCode": "IND" },
  { "name": "Madhya Pradesh", "code": "mp", "countryCode": "IND" },
  { "name": "Maharashtra", "code": "mh", "countryCode": "IND" },
  { "name": "Manipur", "code": "mn", "countryCode": "IND" },
  { "name": "Meghalaya", "code": "ml", "countryCode": "IND" },
  { "name": "Mizoram", "code": "mz", "countryCode": "IND" },
  { "name": "Nagaland", "code": "nl", "countryCode": "IND" },
  { "name": "Odisha", "code": "or", "countryCode": "IND" },
  { "name": "Punjab", "code": "pb", "countryCode": "IND" },
  { "name": "Rajasthan", "code": "rj", "countryCode": "IND" },
  { "name": "Sikkim", "code": "sk", "countryCode": "IND" },
  { "name": "Tamil Nadu", "code": "tn", "countryCode": "IND" },
  { "name": "Telangana", "code": "ts", "countryCode": "IND" },
  { "name": "Tripura", "code": "tr", "countryCode": "IND" },
  { "name": "Uttar Pradesh", "code": "up", "countryCode": "IND" },
  { "name": "Uttarakhand", "code": "uk", "countryCode": "IND" },
  { "name": "West Bengal", "code": "wb", "countryCode": "IND" },
  { "name": "Andaman and Nicobar Islands", "code": "an", "countryCode": "IND" },
  { "name": "Chandigarh", "code": "ch", "countryCode": "IND" },
  { "name": "Dadra and Nagar Haveli and Daman and Diu", "code": "dh", "countryCode": "IND" },
  { "name": "Lakshadweep", "code": "ld", "countryCode": "IND" },
  { "name": "Delhi", "code": "dl", "countryCode": "IND" },
  { "name": "Puducherry", "code": "py", "countryCode": "IND" },
  { "name": "Jammu and Kashmir", "code": "jk", "countryCode": "IND" },
  { "name": "Ladakh", "code": "la", "countryCode": "IND" }
]

export default province;