/**
 * @module CONFIG
 * 
 * Define the API configuration.
 */

import ENV from "./env.config.js";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const __filename = fileURLToPath(import.meta.url); // Get current file path
const __dirname = dirname(__filename); // Get directory path

const CONFIG = {
  // Environment
  NODE_ENV: ENV.NODE_ENV,
  APP_PORT: parseInt(ENV.APP_PORT, 10),

  // Domain
  DOMAINS: {
    PLATFORM_WEB: ENV.PLATFORM_WEB_DOMAIN,
    PLATFORM_BRAND: ENV.PLATFORM_BRAND_DOMAIN,
    CLOUDSTORAGE_DOMAIN: ENV.PLATFORM_CLOUDSTORAGE_DOMAIN
  },

  // Application
  PLATFORM_NAME: ENV.APP_NAME,
  API_VERSION: "v1",
  API_PREFIX: "api/v1",
  PLATFORM_LOG_DIR: join(__dirname, '../../logs'),

  // MongoDB
  MONGODB: {
    URI: ENV.MONGODB_URI,
    NAME: ENV.MONGODB_NAME
  },

  // Redis
  REDIS: {
    URI: ENV.REDIS_URI,
    DB: ENV.REDIS_DB
  },

  // SMTP
  MAILER: {
    SMTP_HOST: ENV.MAILER_SMTP_HOST,
    SMTP_PORT: parseInt(ENV.MAILER_SMTP_PORT, 10),
    USER: ENV.MAILER_USER,
    PASS: ENV.MAILER_PASS,
    SECURE: parseInt(ENV.MAILER_SMTP_PORT, 10) === 465,
    TEMPLATE_DIR: join(__dirname, '../templates')
  },

  // PLATFORM EMAILS
  PLATFORM_MAILS: {
    SUPPORT: ENV.PLATFORM_SUPPORT_MAIL,
    SERVICE: ENV.PLATFORM_SERVICE_MAIL,
  },

  // PLATFORM SOCIALS
  PLATFORM_SOCIALS: {
    FACEBOOK: ENV.PLATFORM_SOCIAL_FACEBOOK,
    TWITTER: ENV.PLATFORM_SOCIAL_TWITTER,
    LINKEDIN: ENV.PLATFORM_SOCIAL_LINKEDIN,
    INSTAGRAM: ENV.PLATFORM_SOCIAL_INSTAGRAM,
    YOUTUBE: ENV.PLATFORM_SOCIAL_YOUTUBE
  },

  // JWT
  JWT: {
    ACCESS_SECRET: ENV.JWT_ACCESS_SECRET,
    REFRESH_SECRET: ENV.JWT_REFRESH_SECRET,
    ACCESS_EXP: ENV.JWT_ACCESS_SECRET_EXPIRES_IN || "1d", // 01 Day
    REFRESH_EXP: ENV.JWT_REFRESH_SECRET_EXPIRES_IN || "7d" // 07 Day
  },

  // AWS
  AWS: {
    ACCESS_KEY: ENV.AWS_ACCESS_KEY,
    SECRET_KEY: ENV.AWS_SECRET_KEY,
    REGION: ENV.AWS_REGION,
    BUCKET: ENV.AWS_BUCKET
  },

  // FIREBASE
  FIREBASE: {
    PROJECT_ID: ENV.FIREBASE_PROJECT_ID,
    CLIENT_EMAIL: ENV.FIREBASE_CLIENT_EMAIL,
    PRIVATE_KEY: ENV.FIREBASE_PRIVATE_KEY,
  },

  // Twilio
  TWILIO: {
    ACCOUNT_SID: ENV.TWILIO_ACCOUNT_SID,
    AUTH_TOKEN: ENV.TWILIO_AUTH_TOKEN,
    PHONE_NUMBER: ENV.TWILIO_PHONE_NUMBER
  },

  // SMS API
  SMS: {
    API_KEY: ENV.SMS_API_KEY,
    API_URL: "https://control.msg91.com/api/v5/flow"
  },
  // SUREPASS
  SUREPASS: {
    TOKEN: ENV.SUREPASS_TOKEN
  },

  // RAZORPAY
  RAZORPAY: {
    API_KEY: ENV.RAZORPAY_API_KEY,
    SECRET: ENV.RAZORPAY_SECRET,
    PLATFORM_ACCOUNT: parseInt(ENV.RAZORPAY_PLATFORM_ACCOUNT, 10)
  },

  // 
  PLATFORM_SESSION: {
    LIMIT: parseInt(ENV.PLATFORM_SESSION_LIMIT, 10)
  },

  // Social
  SOCIALS: {
    GOOGLE: {
      CLIENT_ID: ENV.GOOGLE_CLIENT_ID,
      CLIENT_SECRET: ENV.GOOGLE_CLIENT_SECRET,
      REDIRECT_URI: ENV.GOOGLE_REDIRECT_URI
    },
    FACEBOOK: {
      CLIENT_ID: ENV.FACEBOOK_CLIENT_ID,
      CLIENT_SECRET: ENV.FACEBOOK_CLIENT_SECRET,
      REDIRECT_URI: ENV.FACEBOOK_REDIRECT_URI
    }
  }
}

export default CONFIG;